// apps/solidjs/src/App.tsx
import './App.scss';
import { createSignal, createContext, useContext, Show, createEffect } from 'solid-js';
import * as CanvasData from './canvas-data';
import { Writer, WriteContextProvider, Heading, Paragraph, Fragment, Table, Panel, Code, Image, List, ListItem } from '@contensis/canvas-solid-js';

declare var Prism: any;

const ParagraphContext = createContext<null | { inLede: boolean }>(null);

function MyHeading(props: any) {
    const cssClass = () => `display-${props.item?.properties?.level || '1'}`;
    return <Heading {...props} class={cssClass()} />;
}

function MyParagraph(props: any) {
    const cssClass = () => props.item?.properties?.paragraphType ? 'lead' : null;
    return (
        <ParagraphContext.Provider value={{ inLede: (props.item?.properties?.paragraphType === 'lede') }}>
            <Paragraph {...props} class={cssClass()} />
        </ParagraphContext.Provider>
    );
}

function MyFragment(props: any) {
    const paragraphContext = useContext(ParagraphContext);
    return (paragraphContext?.inLede)
        ? (<Fragment.Children {...props} />)
        : (<Fragment {...props} />);
}

function MyTable(props: any) {
    return <Table {...props} class={'table table-striped'} />
}

const PanelCss: Record<string, string> = {
    'info': 'alert alert-info',
    'note': 'alert alert-primary',
    'warning': 'alert alert-warning',
    'success': 'alert alert-success',
    'error': 'alert alert-danger'
};

function MyPanel(props: any) {
    const panelType = () => props.item?.properties?.panelType || 'info';
    const cssClass = () => PanelCss[panelType()]
    return <Panel {...props} class={cssClass()} />;
}

function MyImage(props: any) {
    const caption = props.item?.value?.caption;
    return (
        <Show when={!!caption} fallback={<Image {...props} class={'img-fluid'} />}>
            <figure class={'figure'} style="display: block">
                <Image {...props} class={'figure-img img-fluid'} />
                <figcaption class={'figure-caption text-end'}>{caption}</figcaption>
            </figure>
        </Show>
    );
}

function MyCode(props: any) {
    const [isCollapsed, setIsCollapsed] = createSignal(false);
    const [isCopying, setIsCopying] = createSignal(false);

    const caption = props.item?.value?.caption;
    const copy = () => {
        setIsCopying(true);
        navigator.clipboard.writeText(props?.item?.value?.code || '');

        setTimeout(() => {
            setIsCopying(false)
        }, 3000);
    };

    const copyButtonText = () => isCopying() ? 'Copied' : 'Copy';

    const expandButtonText = () => isCollapsed() ? 'Expand code' : 'Collapse code';

    const toggle = () => setIsCollapsed(collapsed => !collapsed);

    createEffect(() => {
        if (!isCollapsed()) {
            Prism.highlightAll();
        }
    });

    return (
        <div>
            <div style="display: flex; justify-content: flex-end; gap: 1em;">
                <Show when={!isCollapsed()}>
                    <button disabled={isCopying()} onClick={copy}>{copyButtonText()}</button>
                </Show>
                <button onClick={toggle}>{expandButtonText()}</button>
            </div>
            <Show when={!isCollapsed()}>
                <Show when={!!caption} fallback={<Code {...props} />}>
                    <figure class={'figure'} style="display: block">
                        <Code {...props} />
                        <figcaption class={'figure-caption text-end'}>{caption}</figcaption>
                    </figure>
                </Show>
            </Show>
        </div>
    );
}

export function MyBookComponent(props: any) {
    return (
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{props.item?.value?.name}</h5>
                        <p class="card-text">{props.item?.value?.name}</p>                        
                    </div>
                </div>
                <div class="col-md-4">
                    <img src={props.item?.value?.cover} class="img-fluid rounded-start" />
                </div>
            </div>
        </div>
    );
}

export function MyAuthorComponent(props: any) {
    return (
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src={props.item?.value?.cover} class="img-fluid rounded-start" />
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{props.item?.value?.name}</h5>
                        <p class="card-text">{props.item?.value?.name}</p>                        
                    </div>
                </div>
            </div>
        </div>
    );
}

function MyList(props: any) {
    const cssClass = () => (props?.item?.properties?.listType === 'ordered') ? 'list-group list-group-flush list-group-numbered' : 'list-group list-group-flush';
    return <List {...props} class={cssClass()} />
}


function MyListItem(props: any) {
    return <ListItem {...props} class={'list-group-item'} />
}

const App = () => {
    const [data] = createSignal(CanvasData.data);

    return (
        <div class="content">
            <WriteContextProvider items={{
                _code: MyCode,           
                _fragment: MyFragment,
                _heading: MyHeading,
                _image: MyImage,
                _list: MyList,
                _listItem: MyListItem,
                _panel: MyPanel,
                _paragraph: MyParagraph,
                _table: MyTable
            }}
            components={{
                'author': MyAuthorComponent,
                'book': MyBookComponent
            }}>
                <Writer data={data()} />
            </WriteContextProvider>
        </div>
    );
};

export default App;

// apps/react/src/App.tsx
import './App.css';
import { useState, createContext, useContext, useEffect } from 'react'
import * as CanvasData from './canvas-data';
import { Writer, WriteContextProvider, Heading, Paragraph, Fragment, Table, Panel, Code, Image, List, ListItem } from '@contensis-canvas/react';

declare var Prism: any;

const ParagraphContext = createContext<null | { inLede: boolean }>(null);

export function MyHeading(props: any) {
    const cssClass = `display-${props.item?.properties?.level || '1'}`;
    return <Heading {...props} className={cssClass} />;
}


export function MyParagraph(props: any) {
    const cssClass = props.item?.properties?.paragraphType ? 'lead' : null;
    return (
        <ParagraphContext.Provider value={{ inLede: (props.item?.properties?.paragraphType === 'lede') }}>
            <Paragraph {...props} className={cssClass} />
        </ParagraphContext.Provider>
    );
}

export function MyFragment(props: any) {
    const paragraphContext = useContext(ParagraphContext);
    return (paragraphContext?.inLede)
        ? (<Fragment.Children {...props} />)
        : (<Fragment {...props} />);
}

export function MyTable(props: any) {
    return <Table {...props} className={'table table-striped'} />
}

const PanelCss: Record<string, string> = {
    'info': 'alert alert-info',
    'note': 'alert alert-primary',
    'warning': 'alert alert-warning',
    'success': 'alert alert-success',
    'error': 'alert alert-danger'
};

export function MyPanel(props: any) {
    const panelType = props.item?.properties?.panelType || 'info';
    return <Panel {...props} className={PanelCss[panelType]} />;
}

export function MyImage(props: any) {
    const caption = props.item?.value?.caption;
    return !!caption
        ? (
            <figure className={'figure'} style={{ display: 'block' }}>
                <Image {...props} className={'figure-img img-fluid'} />
                <figcaption className={'figure-caption text-end'}>{caption}</figcaption>
            </figure>
        )
        : (<Image {...props} className={'img-fluid'} />);
}

export function MyCode(props: any) {
    const [isCollapsed, setIsCollapsed] = useState(false);
    const [isCopying, setIsCopying] = useState(false);

    const caption = props.item?.value?.caption;
    const copy = () => {
        setIsCopying(true);
        navigator.clipboard.writeText(props?.item?.value?.code || '');

        setTimeout(() => {
            setIsCopying(false)
        }, 3000);
    };

    const copyButtonText = isCopying ? 'Copied' : 'Copy';
    const expandButtonText = isCollapsed ? 'Expand code' : 'Collapse code';

    const toggle = () => setIsCollapsed(collapsed => !collapsed);

    useEffect(() => {
        if (!isCollapsed) {
            Prism.highlightAll();
        }
    }, [isCollapsed]);

    const codeElement = !!caption
        ? (
            <figure className={'figure'} style={{ display: 'block' }}>
                <Code {...props} />
                <figcaption className={'figure-caption text-end'}>{caption}</figcaption>
            </figure>
        )
        : (<Code {...props} />);

    return (
        <div>
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '1em' }}>
                {isCollapsed ? null : (<button disabled={isCopying} onClick={copy}>{copyButtonText}</button>)}
                <button onClick={toggle}>{expandButtonText}</button>
            </div>
            {isCollapsed ? null : codeElement}
        </div>
    );
}

export function MyBookComponent(props: any) {
    return (
        <div className="card mb-3">
            <div className="row g-0">
                <div className="col-md-8">
                    <div className="card-body">
                        <h5 className="card-title">{props.item?.value?.name}</h5>
                        <p className="card-text">{props.item?.value?.name}</p>                        
                    </div>
                </div>
                <div className="col-md-4">
                    <img src={props.item?.value?.cover} className="img-fluid rounded-start" />
                </div>
            </div>
        </div>
    );
}

export function MyAuthorComponent(props: any) {
    return (
        <div className="card mb-3">
            <div className="row g-0">
                <div className="col-md-4">
                    <img src={props.item?.value?.cover} className="img-fluid rounded-start" />
                </div>
                <div className="col-md-8">
                    <div className="card-body">
                        <h5 className="card-title">{props.item?.value?.name}</h5>
                        <p className="card-text">{props.item?.value?.name}</p>                        
                    </div>
                </div>
            </div>
        </div>
    );
}

function MyList(props: any) {
    const cssClass = (props?.item?.properties?.listType === 'ordered') ? 'list-group list-group-flush list-group-numbered' : 'list-group list-group-flush';
    return <List {...props} className={cssClass} />
}


function MyListItem(props: any) {
    return <ListItem {...props} className={'list-group-item'} />
}

function App() {
    const [data] = useState(CanvasData.data);

    return (
        <div className="content">
            <WriteContextProvider items={{
                _code: MyCode,              
                _fragment: MyFragment,
                _heading: MyHeading,
                _image: MyImage,
                _list: MyList,
                _listItem: MyListItem,
                _panel: MyPanel,
                _paragraph: MyParagraph,
                _table: MyTable
            }}
            components={{
                'author': MyAuthorComponent,
                'book': MyBookComponent
            }}>
                <Writer data={data} />
            </WriteContextProvider>
        </div>
    );
}

export default App;
